set shell := ["nu", "-c"]

build:
    just build-{{ os_family() }}
build-unix:
    g++ main.cpp -o main
build-windows:
    cl /EHsc /W4 /nologo main.cpp

run:
    just run-{{ os_family() }}
run-unix: build-unix
    ./main
run-windows: build-windows
    ./main

watch:
    just watch-{{ os_family() }}
watch-unix:
    watch . { just run-nix } --glob=**/*.cpp
watch-windows:
    watch . { just run-windows } --glob=**/*.cpp
