# zmodload zsh/zprof
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

exists() {
  command -v "$1" >/dev/null 2>&1
}

# disable ZSH beeping like mad
unsetopt beep;

# Disable automatic escaping of pasted URLs
DISABLE_MAGIC_FUNCTIONS=true

# PATH Stuff

export PATH=$HOME/bin:/usr/local/bin:$HOME/.local/bin:$PATH
# prepend in case we need to override system-installed cargo
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$PATH:$HOME/scripts
export PATH=$PATH:$HOME/dotnet
export PATH=$PATH:$HOME/.dotnet/tools
export PATH=$PATH:$HOME/cs-scripts/compiled
export PATH=$PATH:$HOME/.pulumi/bin
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:/home/linuxbrew/.linuxbrew/bin

export ZSH=$HOME/.oh-my-zsh

if exists micro; then
  export EDITOR=micro
  export VISUAL=micro
fi

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="agnoster"
source ~/.powerlevel10k/powerlevel10k.zsh-theme

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"


# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh
source ~/.zsh-plugins/zsh-autosuggestions/zsh-autosuggestions.zsh



export LANG=en_US.UTF-8


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Aliases

alias lg=lazygit
alias mi=micro
alias ddb="duckdb :memory:"

mkd() {
	mkdir $1 && cd $1
}


# zprof